name = "mojang-api"
main = "src/index.ts"
compatibility_date = "2024-12-12"
minify = true

routes = [{ pattern = "api.portero.dev/mojang/v1*", zone_id = "a437aa1e0969de076d0b33cc0d5b34c4" }]

workers_dev = false

account_id = "f336c818d6aa95c5e32d105ee5a0c8c9"
